- name: variables from inventory
  hosts: web
  tasks:
  - name: print variables from inventory
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"
